apiVersion: apps/v1
kind: Deployment
metadata:
  name:  MYAPP
  namespace: default
  labels:
    app:  MYAPP
spec:
  selector:
    matchLabels:
      app: MYAPP
  replicas: 1
  template:
    spec:
      containers:
      - name:  MYAPP
        image:  MYAPP:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CLUSTER
          value: $(CLUSTER)
        - name: url
          value: $(CLUSTER).neuralegion.com
        ports:
        - containerPort:  80
          name:  MYAPP
      restartPolicy: Always